### PR TITLE
Add CurrencyConverter

### PR DESCRIPTION
**Pull request by Advaith3600**
[CurrencyConverter](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter)

This plugin lets you convert real and crypto currencies quickly. 

## Requirements for your pull request

- You have read and understood the [Contribution Guidelines](https://github.com/hlaueriksson/awesome-powertoys-run-plugins/blob/main/contributing.md).
- This pull request has a title in the format `Add [Name of Plugin]`.
  - ✅ `Add GEmojiSharp`
  - ❌ `Update readme.md`
  - ❌ `Adding GEmojiSharp`
  - ❌ `Added GEmojiSharp`
- Your entry should include a short description of the plugin. The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
  - ✅ `- [GEmojiSharp](…) - Find and copy GitHub Emoji to the clipboard.`
  - ❌ `- [GEmojiSharp](…) - A GitHub Emoji plugin for PowerToys Run.`
  - ❌ `- [GEmojiSharp](…)`
- The link text should be the `Name` of the plugin found in the `plugin.json` file. The URL should be the link to the GitHub repo, or a link to an anchor in the readme.
  - ✅ `- [GEmojiSharp](https://github.com/hlaueriksson/GEmojiSharp) - …`
  - ❌ `- [GEmojiSharp.PowerToysRun](…) - …`
  - ❌ `- [GEmojiSharp](https://github.com/hlaueriksson/GEmojiSharp/releases/download/v1.0.0/GEmojiSharp.PowerToysRun.1.0.0.zip) - …`
- Your entry should be added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by Advaith3600** [comment]
@hlaueriksson Did you get a chance to look into the plugin?

**Comment by hlaueriksson** [comment]
Hi @Advaith3600 

Thanks for your contribution!

I have tried the plugin and I could not get it to work on my machine.
I created two issues in your repo.
I hope you have time to take a look.

**Comment by Advaith3600** [comment]
Hey, I have released a new version, [v1.0.2](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/releases/tag/v1.0.2) with all the changes and fixes. Please have a look.

**Comment by hlaueriksson** [comment]
The `v1.0.2` release works great.

Nice plugin! Thanks for your contribution 🚀

**Comment by hlaueriksson** [comment]
Hi @Advaith3600

I just wanted to let you know that this list is now included in the main awesome list.
And that means that you can add a [badge](https://github.com/hlaueriksson/awesome-powertoys-run-plugins/blob/main/contributing.md#awesome-mentioned-badge) to your repo 😎

**Pull request merged**
