### PR TITLE
Add LocalLLM

### PR DESCRIPTION
**Pull request by Darkdriller**
[LocalLLM](https://github.com/Darkdriller/PowerToys-Run-LocalLLm)

 Query LLM models locally through Ollama

## Requirements for your pull request

- You have read and understood the [Contribution Guidelines](https://github.com/hlaueriksson/awesome-powertoys-run-plugins/blob/main/contributing.md).
- This pull request has a title in the format `Add [Name of Plugin]`.
  - ✅ `Add GEmojiSharp`
  - ❌ `Update readme.md`
  - ❌ `Adding GEmojiSharp`
  - ❌ `Added GEmojiSharp`
- Your entry should include a short description of the plugin. The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
  - ✅ `- [GEmojiSharp](…) - Find and copy GitHub Emoji to the clipboard.`
  - ❌ `- [GEmojiSharp](…) - A GitHub Emoji plugin for PowerToys Run.`
  - ❌ `- [GEmojiSharp](…)`
- The link text should be the `Name` of the plugin found in the `plugin.json` file. The URL should be the link to the GitHub repo, or a link to an anchor in the readme.
  - ✅ `- [GEmojiSharp](https://github.com/hlaueriksson/GEmojiSharp) - …`
  - ❌ `- [GEmojiSharp.PowerToysRun](…) - …`
  - ❌ `- [GEmojiSharp](https://github.com/hlaueriksson/GEmojiSharp/releases/download/v1.0.0/GEmojiSharp.PowerToysRun.1.0.0.zip) - …`
- Your entry should be added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by hlaueriksson** [comment]
Hi @Darkdriller

Thanks for your contribution!

Nice plugin!
I have tried it and it works great.
I created two issues with feedback in your repo.
I hope you have time to take a look.

**Comment by Darkdriller** [comment]
Hi @hlaueriksson.

I resolved the conflicts.

**Comment by hlaueriksson** [comment]
You must end the description with a period (`.`), otherwise the repo will not pass the [linter](https://github.com/sindresorhus/awesome-lint). Can you update the PR?

**Comment by hlaueriksson** [comment]
Thanks for your contribution 🚀

**Comment by hlaueriksson** [comment]
Hi @Darkdriller

I just wanted to let you know that this list is now included in the main awesome list.
And that means that you can add a [badge](https://github.com/hlaueriksson/awesome-powertoys-run-plugins/blob/main/contributing.md#awesome-mentioned-badge) to your repo 😎

**Pull request merged**
